const demoData = {
    "subjects": [{
            "subjectDetails": {
                "id": 1,
                "score": 3,
                "acadMonth": "Jul",
                "acadYear": 2019,
                "endDate": "2019-07-04 23:59:00.0",
                "maxAttempt": 1,
                "maxScore": 70,
                "startDate": "2019-05-29 00:00:00.0",
                "maxQuestnToShow": 0,
                "subject": "Organisational Behaviour",
                "errorMessage": "",
                "errorRecord": false,
                "noOfAnswers": 0,
                "batchId": 1,
                "studentTest": {
                    "studentQuestionResponses": [],
                    "student": {
                        "errorMessage": "",
                        "errorRecord": false,
                        "validStudent": false,
                        "waivedOffSubjects": [],
                        "isCorporateExamCenterStudent": false,
                        "purchasedOtherPackages": false
                    },
                    "program": {
                        "errorRecord": false
                    }
                },
                "studentTests": [],
                "students": [],
                "createdBy": "NMSCEMUADMIN01",
                "createdDate": "2019-05-27 17:17:36.0",
                "lastModifiedBy": "NMSCEMUADMIN01",
                "lastModifiedDate": "2019-05-27 17:17:36.0",
            },
            "attemptedTestsList": [{
                    "id": 1,
                    "attempt": 1,
                    "active": "Y",
                    "testStartedOn": "2019-07-13 11:50:52.0",
                    "testEndedOn": "2019-07-13 13:01:55.0",
                    "testCompleted": "Y",
                    "score": 10,
                    "remainingTime": 111,
                    "noOfQuestionsAttempted": 0,
                    "currentQuestion": 1,
                    "maxScore": 10,
                    "scoreInInteger": 0,
                    "testName": "Ob test 1 on generice module updated to IFO",
                    "year": "2019",
                    "month": "Sep",
                    "createdBy": "sanketpanaskar",
                    "createdDate": "2019-06-24 19:59:34.0",
                    "lastModifiedBy": "sanketpanaskar",
                    "lastModifiedDate": "2019-07-13 11:50:44.0",
                    "isScoreSelectedForBestOf7": true,
                },
                {
                    "id": 9,
                    "attempt": 1,
                    "active": "Y",
                    "testStartedOn": "2019-07-16 16:30:28.0",
                    "testEndedOn": "2019-07-16 16:31:57.0",
                    "testCompleted": "Y",
                    "score": 5,
                    "remainingTime": 178,
                    "noOfQuestionsAttempted": 10,
                    "currentQuestion": 65,
                    "maxScore": 10,
                    "scoreInInteger": 0,
                    "testName": "Ob test 2 on generice module updated to IFO",
                    "year": "2019",
                    "month": "Aug",
                    "createdBy": "sanketpanaskar",
                    "createdDate": "2019-07-13 19:25:47.0",
                    "lastModifiedBy": "sanketpanaskar",
                    "lastModifiedDate": "2019-07-13 19:25:47.0",
                    "isScoreSelectedForBestOf7": true,
                },
                {
                    "id": 2,
                    "attempt": 1,
                    "active": "Y",
                    "testStartedOn": "2019-07-16 19:27:52.0",
                    "testEndedOn": "2019-07-16 19:28:49.0",
                    "testCompleted": "Y",
                    "score": 3,
                    "remainingTime": 179,
                    "noOfQuestionsAttempted": 10,
                    "currentQuestion": 98,
                    "maxScore": 10,
                    "scoreInInteger": 1,
                    "testName": "Ob test 3 on generice module updated to IFO",
                    "year": "2019",
                    "month": "Aug",
                    "createdBy": "sanketpanaskar",
                    "createdDate": "2019-07-13 19:10:30.0",
                    "lastModifiedBy": "sanketpanaskar",
                    "lastModifiedDate": "2019-07-13 19:10:30.0",
                    "isScoreSelectedForBestOf7": true,
                },
                {
                    "id": 3,
                    "attempt": 1,
                    "active": "Y",
                    "testStartedOn": "2019-07-16 19:29:34.0",
                    "testEndedOn": "2019-07-16 19:30:23.0",
                    "testCompleted": "Y",
                    "score": 1,
                    "remainingTime": 179,
                    "noOfQuestionsAttempted": 10,
                    "currentQuestion": 140,
                    "maxScore": 10,
                    "scoreInInteger": 1,
                    "testName": "Ob test 1 on generice module updated to HA",
                    "year": "2019",
                    "month": "Aug",
                    "createdBy": "sanketpanaskar",
                    "createdDate": "2019-07-13 19:12:05.0",
                    "lastModifiedBy": "sanketpanaskar",
                    "lastModifiedDate": "2019-07-13 19:12:05.0",
                    "isScoreSelectedForBestOf7": true,
                },
                {
                    "id": 4,
                    "attempt": 1,
                    "active": "Y",
                    "testStartedOn": "2019-07-16 19:31:12.0",
                    "testEndedOn": "2019-07-16 19:32:04.0",
                    "testCompleted": "Y",
                    "score": 7,
                    "remainingTime": 179,
                    "noOfQuestionsAttempted": 10,
                    "currentQuestion": 169,
                    "maxScore": 10,
                    "scoreInInteger": 0,
                    "testName": "Ob test 4 on generice module updated to IFO",
                    "year": "2019",
                    "month": "Aug",
                    "createdBy": "sanketpanaskar",
                    "createdDate": "2019-07-13 19:13:42.0",
                    "lastModifiedBy": "sanketpanaskar",
                    "lastModifiedDate": "2019-07-13 19:13:42.0",
                    "isScoreSelectedForBestOf7": true,
                },
                {
                    "id": 5,
                    "attempt": 1,
                    "active": "Y",
                    "testStartedOn": "2019-07-16 19:34:02.0",
                    "testEndedOn": "2019-07-16 19:34:43.0",
                    "testCompleted": "Y",
                    "score": 5,
                    "remainingTime": 179,
                    "noOfQuestionsAttempted": 7,
                    "currentQuestion": 228,
                    "maxScore": 10,
                    "scoreInInteger": 0,
                    "testName": "Ob test 5 on generice module updated to IFO",
                    "year": "2019",
                    "month": "Aug",
                    "createdBy": "sanketpanaskar",
                    "createdDate": "2019-07-13 19:15:05.0",
                    "lastModifiedBy": "sanketpanaskar",
                    "lastModifiedDate": "2019-07-13 19:15:05.0",
                    "isScoreSelectedForBestOf7": true,
                },
                {
                    "id": 6,
                    "attempt": 1,
                    "active": "Y",
                    "testStartedOn": "2019-07-16 19:36:28.0",
                    "testEndedOn": "2019-07-16 19:37:20.0",
                    "testCompleted": "Y",
                    "score": 2,
                    "remainingTime": 179,
                    "noOfQuestionsAttempted": 10,
                    "currentQuestion": 188,
                    "maxScore": 10,
                    "scoreInInteger": 1,
                    "testName": "Ob test 6 on generice module updated to IFO",
                    "year": "2019",
                    "month": "Aug",
                    "createdBy": "sanketpanaskar",
                    "createdDate": "2019-07-13 19:16:00.0",
                    "lastModifiedBy": "sanketpanaskar",
                    "lastModifiedDate": "2019-07-13 19:16:00.0",
                    "isScoreSelectedForBestOf7": true,
                },
                {
                    "id": 7,
                    "attempt": 0,
                    "active": "Y",
                    "score": 1,
                    "remainingTime": 0,
                    "noOfQuestionsAttempted": 0,
                    "currentQuestion": 0,
                    "maxScore": 10,
                    "scoreInInteger": 0,
                    "testName": "Ob test 7 on generice module updated to IFO",
                    "year": "2019",
                    "month": "Aug",
                    "createdBy": "sanketpanaskar",
                    "createdDate": "2019-07-13 19:18:17.0",
                    "lastModifiedBy": "sanketpanaskar",
                    "lastModifiedDate": "2019-07-13 19:18:17.0",
                    "isScoreSelectedForBestOf7": true,
                },
                {
                    "id": 8,
                    "attempt": 0,
                    "active": "Y",
                    "score": 0,
                    "remainingTime": 0,
                    "noOfQuestionsAttempted": 0,
                    "currentQuestion": 0,
                    "maxScore": 10,
                    "scoreInInteger": 0,
                    "testName": "Ob test 8 on generice module updated to IFO",
                    "year": "2019",
                    "month": "Aug",
                    "createdBy": "sanketpanaskar",
                    "createdDate": "2019-07-13 19:19:45.0",
                    "lastModifiedBy": "sanketpanaskar",
                    "lastModifiedDate": "2019-07-13 19:19:45.0",
                    "isScoreSelectedForBestOf7": false,
                }
            ]
        },
        {
            "subjectDetails": {
                "id": 2,
                "acadMonth": "Jul",
                "acadYear": 2019,
                "endDate": "2019-08-25 23:59:00.0",
                "maxAttempt": 1,
                "startDate": "2019-08-12 00:00:00.0",
                "maxQuestnToShow": 0,
                "subject": "Managerial Economics",
                "errorMessage": "",
                "errorRecord": false,
                "noOfAnswers": 0,
                "batchId": 1,
                "studentTest": {
                    "studentQuestionResponses": [],
                    "student": {
                        "errorMessage": "",
                        "errorRecord": false,
                        "validStudent": false,
                        "waivedOffSubjects": [],
                        "isCorporateExamCenterStudent": false,
                        "purchasedOtherPackages": false
                    },
                    "program": {
                        "errorRecord": false
                    }
                },
                "studentTests": [],
                "students": [],
                "createdBy": "NMSCEMUADMIN01",
                "createdDate": "2019-05-27 17:41:09.0",
                "lastModifiedBy": "NMSCEMUADMIN01",
                "lastModifiedDate": "2019-05-27 17:41:09.0"
            },
            "attemptedTestsList": []
        },
        {
            "subjectDetails": {
                "id": 3,
                "acadMonth": "Jul",
                "acadYear": 2019,
                "endDate": "2019-09-08 23:59:00.0",
                "maxAttempt": 1,
                "startDate": "2019-08-26 00:00:00.0",
                "maxQuestnToShow": 0,
                "subject": "Information Systems for Managers",
                "errorMessage": "",
                "errorRecord": false,
                "noOfAnswers": 0,
                "batchId": 1,
                "studentTest": {
                    "studentQuestionResponses": [],
                    "student": {
                        "errorMessage": "",
                        "errorRecord": false,
                        "validStudent": false,
                        "waivedOffSubjects": [],
                        "isCorporateExamCenterStudent": false,
                        "purchasedOtherPackages": false
                    },
                    "program": {
                        "errorRecord": false
                    }
                },
                "studentTests": [],
                "students": [],
                "createdBy": "NMSCEMUADMIN01",
                "createdDate": "2019-05-27 17:41:09.0",
                "lastModifiedBy": "NMSCEMUADMIN01",
                "lastModifiedDate": "2019-05-27 17:41:09.0"
            },
            "attemptedTestsList": []
        },
        {
            "subjectDetails": {
                "id": 4,
                "acadMonth": "Jul",
                "acadYear": 2019,
                "endDate": "2019-09-22 23:59:00.0",
                "maxAttempt": 1,
                "startDate": "2019-09-09 00:00:00.0",
                "maxQuestnToShow": 0,
                "subject": "Financial Accounting: Information for Decisions",
                "errorMessage": "",
                "errorRecord": false,
                "noOfAnswers": 0,
                "batchId": 1,
                "studentTest": {
                    "studentQuestionResponses": [],
                    "student": {
                        "errorMessage": "",
                        "errorRecord": false,
                        "validStudent": false,
                        "waivedOffSubjects": [],
                        "isCorporateExamCenterStudent": false,
                        "purchasedOtherPackages": false
                    },
                    "program": {
                        "errorRecord": false
                    }
                },
                "studentTests": [],
                "students": [],
                "createdBy": "NMSCEMUADMIN01",
                "createdDate": "2019-05-27 17:41:09.0",
                "lastModifiedBy": "NMSCEMUADMIN01",
                "lastModifiedDate": "2019-05-27 17:41:09.0"
            },
            "attemptedTestsList": []
        },
        {
            "subjectDetails": {
                "id": 5,
                "acadMonth": "Jul",
                "acadYear": 2019,
                "endDate": "2019-10-06 23:59:00.0",
                "maxAttempt": 1,
                "startDate": "2019-09-23 00:00:00.0",
                "maxQuestnToShow": 0,
                "subject": "Marketing Management",
                "errorMessage": "",
                "errorRecord": false,
                "noOfAnswers": 0,
                "batchId": 1,
                "studentTest": {
                    "studentQuestionResponses": [],
                    "student": {
                        "errorMessage": "",
                        "errorRecord": false,
                        "validStudent": false,
                        "waivedOffSubjects": [],
                        "isCorporateExamCenterStudent": false,
                        "purchasedOtherPackages": false
                    },
                    "program": {
                        "errorRecord": false
                    }
                },
                "studentTests": [],
                "students": [],
                "createdBy": "NMSCEMUADMIN01",
                "createdDate": "2019-05-27 17:41:09.0",
                "lastModifiedBy": "NMSCEMUADMIN01",
                "lastModifiedDate": "2019-05-27 17:41:09.0"
            },
            "attemptedTestsList": []
        }
    ]
}
export default demoData